### ISSUE TITLE
line 146 in docs/transactions/index.html, missing letter 't'

### ISSUE THREAD

**Issue by dwt136** [ebean-orm/ebean-orm.github.io#5]
I don't know why but i think it's supposed to be "try".

https://github.com/ebean-orm/ebean-orm.github.io/blob/7cc9b320ad51dba4e0858cc0f4a7f389486fdfa7/docs/transactions/index.html#L146

**Comment by rbygrave** [comment]
Thank you.  I believe this transactions index.html is all good now.  I'll close this.
