### ISSUE TITLE
Eclipse plugin is missing (404)

### ISSUE THREAD

**Issue by aharonha** [ebean-orm/ebean-orm.github.io#7]
in [this page](https://ebean.io/docs/setup/eclipse-apt) theres a broken link to http://ebean.io/eclipse/update

**Comment by rbygrave** [comment]
Thanks.  

Noting that we will redirect users to https://ebean.io/docs/getting-started/eclipse-ide ... as that eclipse ide plugin is no longer maintained.  We prefer users to just add the agent to the JRE.  

The plugin hooks into the compile process and this isn't ideal.  My current thought is to hope that eclipse makes it easier to dynamically add a java agent to a project [to the projects command line as an argument when running tests and main, which is how we do it with IntelliJ these days and that is really quite nice and simple].  The last time I look there wasn't a nice way to do this with eclipse ide.

**Comment by rbygrave** [comment]
Done. Closing.
